frontend:
  build: .
  working_dir: /tmp/bin
  command: python /tmp/frontend.py
  mem_limit: 128m
  cpu_shares: 512
  dns: 8.8.8.8
  links:
   - mongo
   - rabbit
  ports:
   - "8888:8888"
execnode:
  build: .
  working_dir: /tmp/bin
  command: python /tmp/execnode.py foo
  mem_limit: 64m
  cpu_shares: 128 
  links:
   - mongo
   - rabbit
rabbit:
  image: rabbitmq
mongo:
  image: dockerfile/mongodb
  volumes:
   - /tmp:/data/db
